### ISSUE TITLE
Add DQM-like plots for VDT (vertical drift top) coldbox

### ISSUE THREAD

**Issue by dladams** [dladams/vdcoldbox#1]
I would like start looking at VDT coldbox data. First step to to make channel-tick-ADC plots for raw data and pedestal and pedestal RMS vs. channel.

**Comment by dladams** [comment]
I set the tool list in vdtproc.fcl to the following:
<pre>
  digitReader,            # Unpack the digits acd.raw[] and acd.pedestal
  cht_vdtcbu_raw,
  cht_vdtcby_raw,
  cht_vdtcbz_raw,
  vdtcb_adcChannelPedestalPlotter,
  vdtcb_adcChannelRawRmsPlotter
</pre>
The pedestal and RMS plots look good with channel noise correlated to the boundaries:

![image](https://user-images.githubusercontent.com/5585100/187737821-3b99b05a-a19c-4f64-a399-4d1d748089c0.png)

![image](https://user-images.githubusercontent.com/5585100/187737668-e8abf8fc-bfb6-4817-ae63-f3daa3a15964.png)

The ADC vs channel-tick plots look nice except they are missing the boundary lines:
![image](https://user-images.githubusercontent.com/5585100/187738313-00d573a9-75a1-4853-95f4-7393e8933365.png)
![image](https://user-images.githubusercontent.com/5585100/187738427-2f731536-b96e-4415-8cd8-0f979c8ef959.png)
![image](https://user-images.githubusercontent.com/5585100/187738582-40817191-4e52-4964-ac3f-68c19cc2665a.png)
Correlated noise, tracks and a few noisy channels are evident.

I am woking to understand why we don't have the channel boundary lines as in the pedestal and RMS plots.

**Comment by dladams** [comment]
The above plots were made with the command
`./doOneTopEvent vdtproc 1612_1_a 1`

**Comment by wenqiang-gu** [comment]
Hi @dladams , these plots look great. I guess it's because the channel mapping is still not implemented by Slavic so you are not observing boundary lines?

**Comment by dladams** [comment]
No, I need to fix the tool config. But there are two separate issues: channel mapping and the useful boundaries for the plots. We should get both correct.

**Comment by dladams** [comment]
I also notice a logged warning line for each channel from the wire building service apparentslybecause I am not building wires. I will modify the dataprep module to give the option to not build wires. See [dataprep issue 8](https://github.com/DUNE/dunedataprep/issues/8).

**Comment by dladams** [comment]
I did modify DataPrepModule so it does not write the wires but the warning messages still came. I had to add:
<pre>
services.RawDigitPrepService.DoWires: false
</pre>
to stop them.

**Comment by dladams** [comment]
I fixed the cht top plot configs in vdcb_tools.fcl so the detector boundaries now appear in those plots as well. See figures.
![image](https://user-images.githubusercontent.com/5585100/188004388-1b859589-56db-4278-9343-8b3f1d077fa5.png)
![image](https://user-images.githubusercontent.com/5585100/188004460-c21b7caa-83b3-4ba8-b120-61feee29cbb2.png)
![image](https://user-images.githubusercontent.com/5585100/188004505-14c0e7c0-dc2d-4a74-85e4-3882a1355a61.png)

**Comment by dladams** [comment]
I should test all works in the imminent v09_56_01_d00.

**Comment by dladams** [comment]
The above plots are CRP2 data with CRP1 channel map and boundaries. Here are plots showing CRP1 data with the same analysis.
![image](https://user-images.githubusercontent.com/5585100/189223696-c4678b8d-6a98-46d7-bad3-cb461a29260a.png)
![image](https://user-images.githubusercontent.com/5585100/189224132-1631c538-c0f2-4e86-8b21-0ed04446651c.png)
![image](https://user-images.githubusercontent.com/5585100/189224170-51652012-b062-4c45-b2a5-000790e907b7.png)
![image](https://user-images.githubusercontent.com/5585100/189224275-523f3f94-7c59-4842-8ba1-07fcad16d14f.png)
![image](https://user-images.githubusercontent.com/5585100/189224409-430a0925-351d-4cc9-86eb-f78e527e4b8c.png)

**Comment by dladams** [comment]
Code is in place to make plots for CRP1: CRP1B was available long ago and we can now make raw plots for CRP1T. More work is needed for CRP2 but I will open a separate issue for that.
